model = '        Redmi 13C'
partitions = ['efuse.img',
              'crclist.txt',
              'sparsecrclist.txt',
              'preloader_gale.bin',
              'vbmeta.img', 
              'vbmeta_system.img', 
              'vbmeta_vendor.img',
              'md1img.img',
              'spmfw.img',
              'audio_dsp.img',
              'pi_img.img',
              'scp.img',
              'sspm.img',
              'gz.img',
              'lk.img',
              'dtbo.img',
              'tee.img',
              'rescue.img',
              'boot.img', 
              'super.img', 
              'cust.img', 
              'userdata.img']

